spring:
  application:
    name: cards
  config:
    import: "optional:configserver:http://localhost:8071"
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:cardsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework: INFO
    cards.cards: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: cards.cards.controller