spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"


build:
  version: "2.0"

server:
  port: 8082