server:
  port: 8082

spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"

## build with:  mvn compile jib:build
## create db: docker run -p 3307:3306 --name cardsdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cardsdb -d mysql