# Server configuration
server:
  port: 8082
  servlet:
    context-path: /

# Spring configuration
spring:
  application:
    name: teams
  # Database configuration
  datasource:
    url: jdbc:h2:mem:teamsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # H2 console configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# Logging configuration
logging:
  level:
    org.springframework: INFO
    teams.teams: DEBUG

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: teams.teams.controller