# Server configuration
server:
  port: 8082
  servlet:
    context-path: /

# Spring configuration
spring:
  application:
    name: teams
  config:
    import: "optional:configserver:http://localhost:8071"
  profiles:
    active: default
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3037/teamsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # H2 console configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# Build configuration
build:
  version: "1.0.0"

# Logging configuration
logging:
  level:
    org.springframework: INFO
    teams.teams: DEBUG

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: teams.teams.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/