server:
  port: 8081

spring:
  application:
    name: "teams"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/teamsdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

## build with:  mvn compile jib:build
## create db: docker run -p 3308:3306 --name teamsdb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=teamsdb -d mysql