spring:
  config:
    import: "optional:configserver:http://config-server:8071"
  datasource:
    url: jdbc:mysql://users-mysql:3306/usersdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
  instance:
    preferIpAddress: true 