server:
  port: 8071

spring:
  application:
    name: "config-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/configs"

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"