server:
  port: 8071

spring:
  application:
    name: "config-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always