services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  config-server:
    image: "mykyta2/config-server:s1"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  teams:
    image: "mykyta2/teams:s1"
    container_name: teams-ms
    ports:
      - "8081:8081"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "teams"

  cards:
    image: "mykyta2/cards:s1"
    container_name: cards-ms
    ports:
      - "8082:8082"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"

  users:
    image: "mykyta2/users:s1"
    container_name: users-ms
    ports:
      - "8083:8083"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "users"

networks:
  mykyta2:
    driver: "bridge"