build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://cards-mysql:3306/cardsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
  instance:
    preferIpAddress: true